//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenToDo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChildrenDatabaseEntities : DbContext
    {
        public ChildrenDatabaseEntities()
            : base("name=ChildrenDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tNews> tNews { get; set; }
        public virtual DbSet<tBanner> tBanner { get; set; }
        public virtual DbSet<tAbout> tAbout { get; set; }
        public virtual DbSet<tContact> tContact { get; set; }
        public virtual DbSet<tPhoto> tPhoto { get; set; }
        public virtual DbSet<tAdmin> tAdmin { get; set; }
    }
}
