//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChildrenToDo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tAbout
    {
        public int AId { get; set; }
        public string ATitle { get; set; }
        public string AContent { get; set; }
        public Nullable<System.DateTime> ADate { get; set; }
        public string APeople { get; set; }
        public string AsubTitle { get; set; }
        public string APath { get; set; }
    }
}
